Can update entry
johndo-dev/week-planner pull request #4
Opened 2020-10-25 10:22 UTC by jdo697

2020-10-25 10:24 UTC, jdo697 commented
![image](https://user-images.githubusercontent.com/67031107/97104498-93b28d80-1671-11eb-9d8b-4187d400eb32.png)
![image](https://user-images.githubusercontent.com/67031107/97104505-9ca35f00-1671-11eb-8dde-cea2677fd2b1.png)

2021-02-07 21:46 UTC, jdo697 commented
![image](https://user-images.githubusercontent.com/67031107/107160402-d6f7ea00-694a-11eb-8bc3-4e665219aed4.png)

2021-02-07 21:55 UTC, uzair-ashraf requested changes

2021-02-07 21:55 UTC, uzair-ashraf commented on main.js
> +    }
return if its undefined I'm guessing

2021-02-07 21:55 UTC, uzair-ashraf commented on main.js
> +      todoList.addEntry(entryWeek.value, newTask);
If the input is empty, then you're going to get undefined, just make sure its not undefined

2021-02-15 08:30 UTC, jdo697 commented
![F1](https://user-images.githubusercontent.com/67031107/107922519-f7b0d880-6f24-11eb-9fa2-cee775ac6662.gif)
![F2](https://user-images.githubusercontent.com/67031107/107922523-f97a9c00-6f24-11eb-946a-d851f9364fe6.gif)
![F3](https://user-images.githubusercontent.com/67031107/107922529-fb445f80-6f24-11eb-9338-84cbafae04e0.gif)

2021-02-15 08:31 UTC, jdo697 commented
![Untitled](https://user-images.githubusercontent.com/67031107/107922609-1dd67880-6f25-11eb-8b59-1620a755ea67.png)

2021-03-08 11:26 UTC, merged